version: "3.8"
services:
  nginx:
    restart: unless-stopped
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx_image
    ports:
       - '8080:80'
    volumes:
      - ./front:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      
  frontend:
    restart: always
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend_image
    # ports:
    #   - '8080:8080'
    stdin_open: true
    volumes:
      - ./front:/app
      - /app/node_modules
    # command: npm run serve
    expose:
      - "8080"
    environment:
      - HOST=localhost
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    # networks:
    #   - frontend
    depends_on:
      - nginx

  
# networks:
#   frontend:
#     driver: bridge